In [27]:
import pandas as pd

In [28]:
trainMM=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\HMM\MatMul_train_HMM_independent.csv")
testMM=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\HMM\MatMul_test_HMM_independent.csv")
trainPse=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\HMM\PseHMM_train_independent.csv")
testPse=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\HMM\PseHMM_test_independent.csv")

In [29]:
trainMM

,id,sequence,Cell membrane,Cell wall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,...,Feat_391,Feat_392,Feat_393,Feat_394,Feat_395,Feat_396,Feat_397,Feat_398,Feat_399,Feat_400
0,Q38967,MGETAAANNHRHHHHHGHQVFDVASHDFVPPQPAFKCFDDDGRLKR...,1,0,0,0,0,0,0,0,...,0.541165,0.552643,0.578180,0.441778,0.551021,1.193328,0.964984,1.522736,0.433413,1.930418
1,Q9FF99,MDIKEDDESRVITPTELQLHDSVTARTGTLWTAVAHIITGVIGAGV...,1,0,0,0,0,0,0,0,...,0.503441,0.540390,0.501406,0.413377,0.571865,1.131019,0.890804,1.342542,0.439098,1.276387
2,Q8RXN0,MEIEASRQQTTVPVSVGGGNFPVGGLSPLSEAIWREKAPTEFVGDV...,1,0,0,0,0,0,0,0,...,0.737115,0.737035,0.745014,0.630364,0.990965,1.392992,1.061176,1.632994,0.535065,1.924637
3,Q9ZR72,MDNDGGAPPPPPTLVVEEPKKAEIRGVAFKELFRFADGLDYVLMGI...,1,0,0,0,0,0,0,0,...,1.148238,1.424896,1.097432,1.347592,2.020537,2.565835,2.041593,2.914703,0.802023,2.857744
4,Q9FJH6,MVSDASKKKAAQKKAAAAAKRGGKAAAPSKSAATSSNGVDSLSSGV...,1,0,0,0,0,0,0,0,...,0.356498,0.600566,0.536775,0.481717,0.805681,0.927152,0.707951,1.107132,0.184451,1.158151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,P09799,MVRNKSVFVVLLFSLFLSFGLLCSAKDFPGRRSEDDPQQRYEDCRK...,0,0,0,0,0,0,0,0,...,0.293078,0.366442,0.384005,0.761587,1.071461,0.752954,0.625183,1.158346,0.355075,2.050323
3549,P02855,DNAEIEKILLEEHEKETHHRRGLRDKRQQSQEKNVIVKVSKKQIEE...,0,0,0,0,0,0,0,0,...,0.122783,0.226451,0.169053,0.204592,0.304112,0.311897,0.260889,0.459050,0.128738,0.641185
3550,P09801,MVRNKSACVVLLFSLFLSFGLLCSAKDFPGRRGDDDPPKRYEDCRR...,0,0,0,0,0,0,0,0,...,0.294258,0.357376,0.397600,0.877914,1.034990,0.749886,0.596831,1.043025,0.353081,1.835832
3551,P02854,MLLAIAFLASVCVSSRSDQENPFIFKSNRFQTLYENENGHIRLLQK...,0,0,0,0,0,0,0,0,...,0.262092,0.298404,0.385936,0.356204,0.501714,0.568392,0.571648,0.972493,0.243099,0.967227
3552,P13918,MAATTMKASFPLLMLMGISFLASVCVSSRSDPQNPFIFKSNKFQTL...,0,0,0,0,0,0,0,0,...,0.292117,0.314125,0.405992,0.414322,0.578528,0.691778,0.625202,0.970156,0.221585,1.065373

In [30]:
trainMM.dropna(inplace=True)
testMM.dropna(inplace=True)
trainPse.dropna(inplace=True)
testPse.dropna(inplace=True)

In [31]:
C1=[]
for i in range(1,401):
    C1.append("Feat_"+str(i))

In [32]:
XTrainMM=trainMM[C1]
XTestMM=testMM[C1]

In [33]:
C2=[]
for i in range(1,321):
    C2.append("Feat_"+str(i))

In [34]:
XTrainPse=trainPse[C2]
XTestPse=testPse[C2]

In [35]:
XTrainPse.columns=[i for i in range(320)]
XTestPse.columns=[i for i in range(320)]

In [36]:
XTrainMM.columns=[i for i in range(320,720)]
XTestMM.columns=[i for i in range(320,720)]

In [37]:
XTrainPse.reset_index(drop=True, inplace=True)
XTrainMM.reset_index(drop=True, inplace=True)

XTestPse.reset_index(drop=True,inplace=True)
XTestMM.reset_index(drop=True,inplace=True)

In [38]:
Xtrain = XTrainPse.combine_first(XTrainMM)
Xtest=XTestPse.combine_first(XTestMM)

In [39]:
Xtrain.fillna(0,inplace=True)
Xtest.fillna(0,inplace=True)

In [40]:
# Xtrain.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Xtrain.csv")
# Xtest.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Xtest.csv")

In [41]:
trainMM.drop(C1,inplace=True,axis=1)
testMM.drop(C1,inplace=True,axis=1)
trainMM.columns

Index(['id', 'sequence', 'Cell membrane', 'Cell wall', 'Cytoplasm',
       'Endoplasm', 'Extracellular', 'Golgi Apparatus', 'Mitochondrion',
       'Nucleus', 'Peroxisome', 'Plastid', 'Vacuole', 'Length'],
      dtype='object')

In [42]:
testMM.columns

Index(['id', 'sequence', 'Cell membrane', 'Cell wall', 'Cytoplasm',
       'Endoplasm', 'Extracellular', 'Golgi Apparatus', 'Mitochondrion',
       'Nucleus', 'Peroxisome', 'Plastid', 'Vacuole', 'Length'],
      dtype='object')

In [43]:
trainMM

,id,sequence,Cell membrane,Cell wall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole,Length
0,Q38967,MGETAAANNHRHHHHHGHQVFDVASHDFVPPQPAFKCFDDDGRLKR...,1,0,0,0,0,0,0,0,0,0,0,493
1,Q9FF99,MDIKEDDESRVITPTELQLHDSVTARTGTLWTAVAHIITGVIGAGV...,1,0,0,0,0,0,0,0,0,0,0,467
2,Q8RXN0,MEIEASRQQTTVPVSVGGGNFPVGGLSPLSEAIWREKAPTEFVGDV...,1,0,0,0,0,0,0,0,0,0,0,703
3,Q9ZR72,MDNDGGAPPPPPTLVVEEPKKAEIRGVAFKELFRFADGLDYVLMGI...,1,0,0,0,0,0,0,0,0,0,0,1286
4,Q9FJH6,MVSDASKKKAAQKKAAAAAKRGGKAAAPSKSAATSSNGVDSLSSGV...,1,0,0,0,0,0,0,0,0,0,0,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,P09799,MVRNKSVFVVLLFSLFLSFGLLCSAKDFPGRRSEDDPQQRYEDCRK...,0,0,0,0,0,0,0,0,0,0,1,605
3549,P02855,DNAEIEKILLEEHEKETHHRRGLRDKRQQSQEKNVIVKVSKKQIEE...,0,0,0,0,0,0,0,0,0,0,1,275
3550,P09801,MVRNKSACVVLLFSLFLSFGLLCSAKDFPGRRGDDDPPKRYEDCRR...,0,0,0,0,0,0,0,0,0,0,1,588
3551,P02854,MLLAIAFLASVCVSSRSDQENPFIFKSNRFQTLYENENGHIRLLQK...,0,0,0,0,0,0,0,0,0,0,1,410
3552,P13918,MAATTMKASFPLLMLMGISFLASVCVSSRSDPQNPFIFKSNKFQTL...,0,0,0,0,0,0,0,0,0,0,1,459

In [44]:
testMM

,id,sequence,Cell membrane,Cell wall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole,Length
0,Q9SAH3,MPSRPNPTRPKLFHNRTKTLFLILTISSSLVIFFAILYFIYHLWIS...,1,0,0,0,0,0,0,0,0,0,0,692
1,Q9ASQ6,MSIILWSFFLFFTIILSSLTNITTLASFSSLHADELNALKEIATTL...,1,0,0,0,0,0,0,0,0,0,0,1019
2,Q9SIZ4,MLFKMRSFVAFVLLLSWFGSCCSLKDQAVDFLKSEDSLKKDLSSDE...,1,0,0,0,0,0,0,0,0,0,0,489
3,Q9ZQQ7,METRSKLMLLACATFSIISLVKSQNQQGFISLYCGLPSNESPYIEP...,1,0,0,0,0,0,0,0,0,0,0,886
4,C0LGK4,MVDQRRSALGFVLLLLCLVLFFDCVVVGQTQSRFSEKLILLNLRSS...,1,0,0,0,0,0,0,0,0,0,0,915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,Q9LSF6,MTSNVQLSETNSPRNQKTRPRAEKEEVDYMQRAQWLRAALLGANDG...,0,0,0,0,0,0,0,0,0,0,1,219
622,Q9FRK5,MADSQNGKSAFFFFFVSLILLFLSPSYSDVTASESDPIPYENSDAS...,0,0,0,0,0,0,0,0,0,0,1,617
623,P06673,MKMVIVLVVWLALSAASASAMQMPCPCAGLQGLYGAGAGLTTMMGA...,0,0,0,0,0,0,0,0,0,0,1,180
624,P08031,MKVLIVALALLALAASAASSTSGGCGCQTPPFHLPPPFYMPPPFYL...,0,0,0,0,0,0,0,0,0,0,1,183
625,Q8RWN2,MAEEYKEALLEKQNYHDGCPGCKVEQMKQLRRGYPYLELSFVWIIV...,0,0,0,0,0,0,0,0,0,0,1,486

In [45]:
trainMM.drop([ 'Length', 'id','sequence'],axis=1,inplace=True)
testMM.drop(['Length', 'id','sequence'],axis=1,inplace=True)

In [46]:
Ytrain=trainMM
Ytest=testMM

In [47]:
# Ytrain.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Ytrain.csv")
# Ytest.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Ytest.csv")

In [48]:

Ytrain

,Cell membrane,Cell wall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3548,0,0,0,0,0,0,0,0,0,0,1
3549,0,0,0,0,0,0,0,0,0,0,1
3550,0,0,0,0,0,0,0,0,0,0,1
3551,0,0,0,0,0,0,0,0,0,0,1
3552,0,0,0,0,0,0,0,0,0,0,1

In [49]:
Ytest

,Cell membrane,Cell wall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
621,0,0,0,0,0,0,0,0,0,0,1
622,0,0,0,0,0,0,0,0,0,0,1
623,0,0,0,0,0,0,0,0,0,0,1
624,0,0,0,0,0,0,0,0,0,0,1
625,0,0,0,0,0,0,0,0,0,0,1

In [50]:
col=[]
for m in Ytrain.columns:
    col.append(m)

In [51]:
models=[]
from sklearn.ensemble import RandomForestClassifier

for i in range(len(col)):
    clf = RandomForestClassifier(n_estimators = 150) 
    clf.fit(Xtrain,Ytrain[col[i]])
    models.append(clf)

In [52]:
models1=[]
for c in Ytest.columns:
    models1.append(models[col.index(c)])

In [53]:
for i in range(len(Ytest.columns)):
    print(models1[i].score(Xtest, Ytest[Ytest.columns[i]]))

0.9009584664536742
0.9728434504792333
0.9041533546325878
0.9712460063897763
0.9888178913738019
0.9329073482428115
0.8594249201277955
0.9281150159744409
0.9904153354632588
0.694888178913738
0.9840255591054313

In [54]:
col1=[]
for i in range(len(Ytest.columns)):
    col1.append(Ytest.columns[i])

In [55]:
dd=[]
for i in range(len(models1)):
    dd.append(models1[i].predict(Xtest))

In [56]:
data_f = pd.DataFrame(dd,index=Ytest.columns)

In [57]:
data_f=data_f.transpose()

In [58]:
Ytest=Ytest.reset_index()

In [59]:
data_f.columns

Index(['Cell membrane', 'Cell wall', 'Cytoplasm', 'Endoplasm', 'Extracellular',
       'Golgi Apparatus', 'Mitochondrion', 'Nucleus', 'Peroxisome', 'Plastid',
       'Vacuole'],
      dtype='object')

In [60]:
Ytest.drop("index",inplace=True,axis=1)

In [61]:
sum=0
for i in range(len(Ytest)):
    sum+=(data_f.iloc[i,:]==Ytest.iloc[i,:]).all()
sum/len(Ytest)

0.2939297124600639

In [62]:
sum1=0
for i in range(len(Ytest)):
    c=0
    for j in range(len(Ytest.iloc[i])):
        if Ytest.iloc[i][j]==data_f.iloc[i][j]:
            c+=1
    sum1=sum1+c/len(Ytest.iloc[i])

sum1/len(Ytest)

0.9207086842869625