In [1]:
import pandas as pd

In [2]:
trainMM=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\MatMul_train_PSSM_independent.csv")
testMM=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\MatMul_test_PSSM_independent.csv")
trainPse=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\PsePSSM_train_independent.csv")
testPse=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\PsePSSM_test_independent.csv")

In [3]:
trainMM

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,...,Feat_391,Feat_392,Feat_393,Feat_394,Feat_395,Feat_396,Feat_397,Feat_398,Feat_399,Feat_400
0,Q38967,MGETAAANNHRHHHHHGHQVFDVASHDFVPPQPAFKCFDDDGRLKR...,1,0,0,0,0,0,0,0,...,4348.0,965.0,3594.0,2897.0,1707.0,385.0,1935.0,2215.0,1662.0,5653.0
1,Q9FF99,MDIKEDDESRVITPTELQLHDSVTARTGTLWTAVAHIITGVIGAGV...,1,0,0,0,0,0,0,0,...,4655.0,1273.0,3909.0,3280.0,2056.0,568.0,2135.0,2473.0,1982.0,5992.0
2,Q8RXN0,MEIEASRQQTTVPVSVGGGNFPVGGLSPLSEAIWREKAPTEFVGDV...,1,0,0,0,0,0,0,0,...,6152.0,1483.0,5334.0,4339.0,3023.0,520.0,2894.0,4260.0,2709.0,8019.0
3,Q9ZR72,MDNDGGAPPPPPTLVVEEPKKAEIRGVAFKELFRFADGLDYVLMGI...,1,0,0,0,0,0,0,0,...,13407.0,1422.0,11405.0,10797.0,6536.0,731.0,5902.0,10064.0,7908.0,17731.0
4,Q9FJH6,MVSDASKKKAAQKKAAAAAKRGGKAAAPSKSAATSSNGVDSLSSGV...,1,0,0,0,0,0,0,0,...,4957.0,29.0,3867.0,4174.0,2168.0,629.0,2104.0,3947.0,2931.0,5869.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,P09799,MVRNKSVFVVLLFSLFLSFGLLCSAKDFPGRRSEDDPQQRYEDCRK...,0,0,0,0,0,0,0,0,...,3838.0,-764.0,3002.0,3172.0,426.0,-207.0,1434.0,2262.0,1915.0,4642.0
3549,P02855,DNAEIEKILLEEHEKETHHRRGLRDKRQQSQEKNVIVKVSKKQIEE...,0,0,0,0,0,0,0,0,...,1424.0,-464.0,1080.0,1016.0,126.0,-293.0,384.0,911.0,728.0,1885.0
3550,P09801,MVRNKSACVVLLFSLFLSFGLLCSAKDFPGRRGDDDPPKRYEDCRR...,0,0,0,0,0,0,0,0,...,3500.0,-685.0,2866.0,3054.0,317.0,-144.0,1325.0,2185.0,1824.0,4333.0
3551,P02854,MLLAIAFLASVCVSSRSDQENPFIFKSNRFQTLYENENGHIRLLQK...,0,0,0,0,0,0,0,0,...,2126.0,-434.0,1647.0,1545.0,-14.0,-455.0,543.0,1156.0,993.0,2765.0
3552,P13918,MAATTMKASFPLLMLMGISFLASVCVSSRSDPQNPFIFKSNKFQTL...,0,0,0,0,0,0,0,0,...,2399.0,-540.0,1877.0,1753.0,20.0,-505.0,671.0,1477.0,1194.0,3065.0

In [4]:
trainMM.dropna(inplace=True)
testMM.dropna(inplace=True)
trainPse.dropna(inplace=True)
testPse.dropna(inplace=True)

In [5]:
C1=[]
for i in range(1,401):
    C1.append("Feat_"+str(i))

In [6]:
XTrainMM=trainMM[C1]
XTestMM=testMM[C1]

In [7]:
C2=[]
for i in range(1,321):
    C2.append("Feat_"+str(i))

In [8]:
XTrainPse=trainPse[C2]
XTestPse=testPse[C2]

In [9]:
XTrainPse.columns=[i for i in range(320)]
XTestPse.columns=[i for i in range(320)]

In [10]:
XTrainMM.columns=[i for i in range(320,720)]
XTestMM.columns=[i for i in range(320,720)]

In [11]:
XTrainPse.reset_index(drop=True, inplace=True)
XTrainMM.reset_index(drop=True, inplace=True)

XTestPse.reset_index(drop=True,inplace=True)
XTestMM.reset_index(drop=True,inplace=True)

In [12]:
Xtrain = XTrainPse.combine_first(XTrainMM)
Xtest=XTestPse.combine_first(XTestMM)

In [13]:
# Xtrain.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Xtrain.csv")
# Xtest.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Xtest.csv")

In [14]:
trainMM.drop(C1,inplace=True,axis=1)
testMM.drop(C1,inplace=True,axis=1)
trainMM.columns

Index(['id', 'sequence', 'Cellmembrane', 'Cellwall', 'Cytoplasm', 'Endoplasm',
       'Extracellular', 'Golgi Apparatus', 'Mitochondrion', 'Nucleus',
       'Peroxisome', 'Plastid', 'Vacuole', 'Length'],
      dtype='object')

In [15]:
testMM.columns

Index(['id', 'sequence', 'Cellmembrane', 'Cellwall', 'Cytoplasm', 'Endoplasm',
       'Extracellular', 'Golgi Apparatus', 'Mitochondrion', 'Nucleus',
       'Peroxisome', 'Plastid', 'Vacuole', 'Length'],
      dtype='object')

In [16]:
trainMM

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole,Length
0,Q38967,MGETAAANNHRHHHHHGHQVFDVASHDFVPPQPAFKCFDDDGRLKR...,1,0,0,0,0,0,0,0,0,0,0,493
1,Q9FF99,MDIKEDDESRVITPTELQLHDSVTARTGTLWTAVAHIITGVIGAGV...,1,0,0,0,0,0,0,0,0,0,0,467
2,Q8RXN0,MEIEASRQQTTVPVSVGGGNFPVGGLSPLSEAIWREKAPTEFVGDV...,1,0,0,0,0,0,0,0,0,0,0,703
3,Q9ZR72,MDNDGGAPPPPPTLVVEEPKKAEIRGVAFKELFRFADGLDYVLMGI...,1,0,0,0,0,0,0,0,0,0,0,1286
4,Q9FJH6,MVSDASKKKAAQKKAAAAAKRGGKAAAPSKSAATSSNGVDSLSSGV...,1,0,0,0,0,0,0,0,0,0,0,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,P09799,MVRNKSVFVVLLFSLFLSFGLLCSAKDFPGRRSEDDPQQRYEDCRK...,0,0,0,0,0,0,0,0,0,0,1,605
3549,P02855,DNAEIEKILLEEHEKETHHRRGLRDKRQQSQEKNVIVKVSKKQIEE...,0,0,0,0,0,0,0,0,0,0,1,275
3550,P09801,MVRNKSACVVLLFSLFLSFGLLCSAKDFPGRRGDDDPPKRYEDCRR...,0,0,0,0,0,0,0,0,0,0,1,588
3551,P02854,MLLAIAFLASVCVSSRSDQENPFIFKSNRFQTLYENENGHIRLLQK...,0,0,0,0,0,0,0,0,0,0,1,410
3552,P13918,MAATTMKASFPLLMLMGISFLASVCVSSRSDPQNPFIFKSNKFQTL...,0,0,0,0,0,0,0,0,0,0,1,459

In [17]:
testMM

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole,Length
0,Q9SAH3,MPSRPNPTRPKLFHNRTKTLFLILTISSSLVIFFAILYFIYHLWIS...,1,0,0,0,0,0,0,0,0,0,0,692
1,Q9ASQ6,MSIILWSFFLFFTIILSSLTNITTLASFSSLHADELNALKEIATTL...,1,0,0,0,0,0,0,0,0,0,0,1019
2,Q9SIZ4,MLFKMRSFVAFVLLLSWFGSCCSLKDQAVDFLKSEDSLKKDLSSDE...,1,0,0,0,0,0,0,0,0,0,0,489
3,Q9ZQQ7,METRSKLMLLACATFSIISLVKSQNQQGFISLYCGLPSNESPYIEP...,1,0,0,0,0,0,0,0,0,0,0,886
4,C0LGK4,MVDQRRSALGFVLLLLCLVLFFDCVVVGQTQSRFSEKLILLNLRSS...,1,0,0,0,0,0,0,0,0,0,0,915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,Q9LSF6,MTSNVQLSETNSPRNQKTRPRAEKEEVDYMQRAQWLRAALLGANDG...,0,0,0,0,0,0,0,0,0,0,1,219
622,Q9FRK5,MADSQNGKSAFFFFFVSLILLFLSPSYSDVTASESDPIPYENSDAS...,0,0,0,0,0,0,0,0,0,0,1,617
623,P06673,MKMVIVLVVWLALSAASASAMQMPCPCAGLQGLYGAGAGLTTMMGA...,0,0,0,0,0,0,0,0,0,0,1,180
624,P08031,MKVLIVALALLALAASAASSTSGGCGCQTPPFHLPPPFYMPPPFYL...,0,0,0,0,0,0,0,0,0,0,1,183
625,Q8RWN2,MAEEYKEALLEKQNYHDGCPGCKVEQMKQLRRGYPYLELSFVWIIV...,0,0,0,0,0,0,0,0,0,0,1,486

In [18]:
trainMM.drop([ 'Length', 'id','sequence'],axis=1,inplace=True)
testMM.drop(['Length', 'id','sequence'],axis=1,inplace=True)

In [19]:
Ytrain=trainMM
Ytest=testMM

In [20]:
# Ytrain.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Ytrain.csv")
# Ytest.to_csv(r"c:\Users\nagar\OneDrive\Desktop\data\Ytest.csv")

In [21]:

Ytrain

,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3548,0,0,0,0,0,0,0,0,0,0,1
3549,0,0,0,0,0,0,0,0,0,0,1
3550,0,0,0,0,0,0,0,0,0,0,1
3551,0,0,0,0,0,0,0,0,0,0,1
3552,0,0,0,0,0,0,0,0,0,0,1

In [22]:
Ytest

,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
621,0,0,0,0,0,0,0,0,0,0,1
622,0,0,0,0,0,0,0,0,0,0,1
623,0,0,0,0,0,0,0,0,0,0,1
624,0,0,0,0,0,0,0,0,0,0,1
625,0,0,0,0,0,0,0,0,0,0,1

In [23]:
col=[]
for m in Ytrain.columns:
    col.append(m)

In [24]:
models=[]
from sklearn.tree import DecisionTreeClassifier

for i in range(len(col)):
    clf = DecisionTreeClassifier()
    clf.fit(Xtrain,Ytrain[col[i]])
    models.append(clf)

In [25]:
models1=[]
for c in Ytest.columns:
    models1.append(models[col.index(c)])

In [26]:
for i in range(len(Ytest.columns)):
    print(models1[i].score(Xtest, Ytest[Ytest.columns[i]]))

0.7892074198988196
0.9881956155143339
0.8010118043844857
0.9409780775716695
0.9713322091062394
0.924114671163575
0.8145025295109612
0.8246205733558178
0.9426644182124789
0.7335581787521079
0.9258010118043845

In [27]:
col1=[]
for i in range(len(Ytest.columns)):
    col1.append(Ytest.columns[i])

In [28]:
dd=[]
for i in range(len(models1)):
    dd.append(models1[i].predict(Xtest))

In [29]:
data_f = pd.DataFrame(dd,index=Ytest.columns)

In [30]:
data_f=data_f.transpose()

In [31]:
Ytest=Ytest.reset_index()

In [32]:
data_f.columns

Index(['Cellmembrane', 'Cellwall', 'Cytoplasm', 'Endoplasm', 'Extracellular',
       'Golgi Apparatus', 'Mitochondrion', 'Nucleus', 'Peroxisome', 'Plastid',
       'Vacuole'],
      dtype='object')

In [33]:
Ytest.drop("index",inplace=True,axis=1)

In [34]:
sum=0
for i in range(len(Ytest)):
    sum+=(data_f.iloc[i,:]==Ytest.iloc[i,:]).all()
sum/len(Ytest)

0.2866779089376054

In [35]:
sum1=0
for i in range(len(Ytest)):
    c=0
    for j in range(len(Ytest.iloc[i])):
        if Ytest.iloc[i][j]==data_f.iloc[i][j]:
            c+=1
    sum1=sum1+c/len(Ytest.iloc[i])

sum1/len(Ytest)

0.8778169553886286