In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\MatMul_train_PSSM_independent.csv")
df2=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\MatMul_test_PSSM_independent.csv")

In [3]:
df1

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,...,Feat_391,Feat_392,Feat_393,Feat_394,Feat_395,Feat_396,Feat_397,Feat_398,Feat_399,Feat_400
0,Q38967,MGETAAANNHRHHHHHGHQVFDVASHDFVPPQPAFKCFDDDGRLKR...,1,0,0,0,0,0,0,0,...,4348.0,965.0,3594.0,2897.0,1707.0,385.0,1935.0,2215.0,1662.0,5653.0
1,Q9FF99,MDIKEDDESRVITPTELQLHDSVTARTGTLWTAVAHIITGVIGAGV...,1,0,0,0,0,0,0,0,...,4655.0,1273.0,3909.0,3280.0,2056.0,568.0,2135.0,2473.0,1982.0,5992.0
2,Q8RXN0,MEIEASRQQTTVPVSVGGGNFPVGGLSPLSEAIWREKAPTEFVGDV...,1,0,0,0,0,0,0,0,...,6152.0,1483.0,5334.0,4339.0,3023.0,520.0,2894.0,4260.0,2709.0,8019.0
3,Q9ZR72,MDNDGGAPPPPPTLVVEEPKKAEIRGVAFKELFRFADGLDYVLMGI...,1,0,0,0,0,0,0,0,...,13407.0,1422.0,11405.0,10797.0,6536.0,731.0,5902.0,10064.0,7908.0,17731.0
4,Q9FJH6,MVSDASKKKAAQKKAAAAAKRGGKAAAPSKSAATSSNGVDSLSSGV...,1,0,0,0,0,0,0,0,...,4957.0,29.0,3867.0,4174.0,2168.0,629.0,2104.0,3947.0,2931.0,5869.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,P09799,MVRNKSVFVVLLFSLFLSFGLLCSAKDFPGRRSEDDPQQRYEDCRK...,0,0,0,0,0,0,0,0,...,3838.0,-764.0,3002.0,3172.0,426.0,-207.0,1434.0,2262.0,1915.0,4642.0
3549,P02855,DNAEIEKILLEEHEKETHHRRGLRDKRQQSQEKNVIVKVSKKQIEE...,0,0,0,0,0,0,0,0,...,1424.0,-464.0,1080.0,1016.0,126.0,-293.0,384.0,911.0,728.0,1885.0
3550,P09801,MVRNKSACVVLLFSLFLSFGLLCSAKDFPGRRGDDDPPKRYEDCRR...,0,0,0,0,0,0,0,0,...,3500.0,-685.0,2866.0,3054.0,317.0,-144.0,1325.0,2185.0,1824.0,4333.0
3551,P02854,MLLAIAFLASVCVSSRSDQENPFIFKSNRFQTLYENENGHIRLLQK...,0,0,0,0,0,0,0,0,...,2126.0,-434.0,1647.0,1545.0,-14.0,-455.0,543.0,1156.0,993.0,2765.0
3552,P13918,MAATTMKASFPLLMLMGISFLASVCVSSRSDPQNPFIFKSNKFQTL...,0,0,0,0,0,0,0,0,...,2399.0,-540.0,1877.0,1753.0,20.0,-505.0,671.0,1477.0,1194.0,3065.0

In [4]:
df2

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,...,Feat_391,Feat_392,Feat_393,Feat_394,Feat_395,Feat_396,Feat_397,Feat_398,Feat_399,Feat_400
0,Q9SAH3,MPSRPNPTRPKLFHNRTKTLFLILTISSSLVIFFAILYFIYHLWIS...,1,0,0,0,0,0,0,0,...,4274.0,-207.0,3577.0,3549.0,1631.0,1.0,1985.0,2361.0,2707.0,5470.0
1,Q9ASQ6,MSIILWSFFLFFTIILSSLTNITTLASFSSLHADELNALKEIATTL...,1,0,0,0,0,0,0,0,...,12658.0,4364.0,11036.0,11507.0,8382.0,3012.0,6795.0,11645.0,8715.0,15698.0
2,Q9SIZ4,MLFKMRSFVAFVLLLSWFGSCCSLKDQAVDFLKSEDSLKKDLSSDE...,1,0,0,0,0,0,0,0,...,3377.0,126.0,2839.0,2572.0,1027.0,-291.0,1253.0,2372.0,1724.0,4258.0
3,Q9ZQQ7,METRSKLMLLACATFSIISLVKSQNQQGFISLYCGLPSNESPYIEP...,1,0,0,0,0,0,0,0,...,8467.0,2198.0,7411.0,6932.0,4705.0,1473.0,4172.0,6581.0,4294.0,11141.0
4,C0LGK4,MVDQRRSALGFVLLLLCLVLFFDCVVVGQTQSRFSEKLILLNLRSS...,1,0,0,0,0,0,0,0,...,9184.0,3541.0,8599.0,7807.0,5031.0,842.0,5379.0,8260.0,6138.0,12159.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,Q9LSF6,MTSNVQLSETNSPRNQKTRPRAEKEEVDYMQRAQWLRAALLGANDG...,0,0,0,0,0,0,0,0,...,2165.0,346.0,1731.0,1773.0,701.0,-46.0,870.0,1309.0,1209.0,2845.0
622,Q9FRK5,MADSQNGKSAFFFFFVSLILLFLSPSYSDVTASESDPIPYENSDAS...,0,0,0,0,0,0,0,0,...,2763.0,-561.0,2118.0,2146.0,119.0,-511.0,623.0,1661.0,1139.0,3464.0
623,P06673,MKMVIVLVVWLALSAASASAMQMPCPCAGLQGLYGAGAGLTTMMGA...,0,0,0,0,0,0,0,0,...,495.0,-82.0,380.0,369.0,-157.0,-95.0,86.0,151.0,123.0,514.0
624,P08031,MKVLIVALALLALAASAASSTSGGCGCQTPPFHLPPPFYMPPPFYL...,0,0,0,0,0,0,0,0,...,613.0,4.0,501.0,543.0,-323.0,-51.0,183.0,394.0,247.0,695.0
625,Q8RWN2,MAEEYKEALLEKQNYHDGCPGCKVEQMKQLRRGYPYLELSFVWIIV...,0,0,0,0,0,0,0,0,...,3843.0,1141.0,3328.0,2878.0,1134.0,601.0,1850.0,2582.0,2182.0,4965.0

In [5]:
df1.dropna(inplace=True)
df2.dropna(inplace=True)

In [6]:
C=[]
for i in range(1,401):
    C.append("Feat_"+str(i))
C

['Feat_1',
 'Feat_2',
 'Feat_3',
 'Feat_4',
 'Feat_5',
 'Feat_6',
 'Feat_7',
 'Feat_8',
 'Feat_9',
 'Feat_10',
 'Feat_11',
 'Feat_12',
 'Feat_13',
 'Feat_14',
 'Feat_15',
 'Feat_16',
 'Feat_17',
 'Feat_18',
 'Feat_19',
 'Feat_20',
 'Feat_21',
 'Feat_22',
 'Feat_23',
 'Feat_24',
 'Feat_25',
 'Feat_26',
 'Feat_27',
 'Feat_28',
 'Feat_29',
 'Feat_30',
 'Feat_31',
 'Feat_32',
 'Feat_33',
 'Feat_34',
 'Feat_35',
 'Feat_36',
 'Feat_37',
 'Feat_38',
 'Feat_39',
 'Feat_40',
 'Feat_41',
 'Feat_42',
 'Feat_43',
 'Feat_44',
 'Feat_45',
 'Feat_46',
 'Feat_47',
 'Feat_48',
 'Feat_49',
 'Feat_50',
 'Feat_51',
 'Feat_52',
 'Feat_53',
 'Feat_54',
 'Feat_55',
 'Feat_56',
 'Feat_57',
 'Feat_58',
 'Feat_59',
 'Feat_60',
 'Feat_61',
 'Feat_62',
 'Feat_63',
 'Feat_64',
 'Feat_65',
 'Feat_66',
 'Feat_67',
 'Feat_68',
 'Feat_69',
 'Feat_70',
 'Feat_71',
 'Feat_72',
 'Feat_73',
 'Feat_74',
 'Feat_75',
 'Feat_76',
 'Feat_77',
 'Feat_78',
 'Feat_79',
 'Feat_80',
 'Feat_81',
 'Feat_82',
 'Feat_83',
 'Feat_84',
 'Feat_85',
 'Feat_86',
 'Feat_87',
 'Feat_88',
 'Feat_89',
 'Feat_90',
 'Feat_91',
 'Feat_92',
 'Feat_93',
 'Feat_94',
 'Feat_95',
 'Feat_96',
 'Feat_97',
 'Feat_98',
 'Feat_99',
 'Feat_100',
 'Feat_101',
 'Feat_102',
 'Feat_103',
 'Feat_104',
 'Feat_105',
 'Feat_106',
 'Feat_107',
 'Feat_108',
 'Feat_109',
 'Feat_110',
 'Feat_111',
 'Feat_112',
 'Feat_113',
 'Feat_114',
 'Feat_115',
 'Feat_116',
 'Feat_117',
 'Feat_118',
 'Feat_119',
 'Feat_120',
 'Feat_121',
 'Feat_122',
 'Feat_123',
 'Feat_124',
 'Feat_125',
 'Feat_126',
 'Feat_127',
 'Feat_128',
 'Feat_129',
 'Feat_130',
 'Feat_131',
 'Feat_132',
 'Feat_133',
 'Feat_134',
 'Feat_135',
 'Feat_136',
 'Feat_137',
 'Feat_138',
 'Feat_139',
 'Feat_140',
 'Feat_141',
 'Feat_142',
 'Feat_143',
 'Feat_144',
 'Feat_145',
 'Feat_146',
 'Feat_147',
 'Feat_148',
 'Feat_149',
 'Feat_150',
 'Feat_151',
 'Feat_152',
 'Feat_153',
 'Feat_154',
 'Feat_155',
 'Feat_156',
 'Feat_157',
 'Feat_158',
 'Feat_159',
 'Feat_160',
 'Feat_161',
 'Feat_162',
 'Feat_163',
 'Feat_164',
 'Feat_165',
 'Feat_166',
 'Feat_167',
 'Feat_168',
 'Feat_169',
 'Feat_170',
 'Feat_171',
 'Feat_172',
 'Feat_173',
 'Feat_174',
 'Feat_175',
 'Feat_176',
 'Feat_177',
 'Feat_178',
 'Feat_179',
 'Feat_180',
 'Feat_181',
 'Feat_182',
 'Feat_183',
 'Feat_184',
 'Feat_185',
 'Feat_186',
 'Feat_187',
 'Feat_188',
 'Feat_189',
 'Feat_190',
 'Feat_191',
 'Feat_192',
 'Feat_193',
 'Feat_194',
 'Feat_195',
 'Feat_196',
 'Feat_197',
 'Feat_198',
 'Feat_199',
 'Feat_200',
 'Feat_201',
 'Feat_202',
 'Feat_203',
 'Feat_204',
 'Feat_205',
 'Feat_206',
 'Feat_207',
 'Feat_208',
 'Feat_209',
 'Feat_210',
 'Feat_211',
 'Feat_212',
 'Feat_213',
 'Feat_214',
 'Feat_215',
 'Feat_216',
 'Feat_217',
 'Feat_218',
 'Feat_219',
 'Feat_220',
 'Feat_221',
 'Feat_222',
 'Feat_223',
 'Feat_224',
 'Feat_225',
 'Feat_226',
 'Feat_227',
 'Feat_228',
 'Feat_229',
 'Feat_230',
 'Feat_231',
 'Feat_232',
 'Feat_233',
 'Feat_234',
 'Feat_235',
 'Feat_236',
 'Feat_237',
 'Feat_238',
 'Feat_239',
 'Feat_240',
 'Feat_241',
 'Feat_242',
 'Feat_243',
 'Feat_244',
 'Feat_245',
 'Feat_246',
 'Feat_247',
 'Feat_248',
 'Feat_249',
 'Feat_250',
 'Feat_251',
 'Feat_252',
 'Feat_253',
 'Feat_254',
 'Feat_255',
 'Feat_256',
 'Feat_257',
 'Feat_258',
 'Feat_259',
 'Feat_260',
 'Feat_261',
 'Feat_262',
 'Feat_263',
 'Feat_264',
 'Feat_265',
 'Feat_266',
 'Feat_267',
 'Feat_268',
 'Feat_269',
 'Feat_270',
 'Feat_271',
 'Feat_272',
 'Feat_273',
 'Feat_274',
 'Feat_275',
 'Feat_276',
 'Feat_277',
 'Feat_278',
 'Feat_279',
 'Feat_280',
 'Feat_281',
 'Feat_282',
 'Feat_283',
 'Feat_284',
 'Feat_285',
 'Feat_286',
 'Feat_287',
 'Feat_288',
 'Feat_289',
 'Feat_290',
 'Feat_291',
 'Feat_292',
 'Feat_293',
 'Feat_294',
 'Feat_295',
 'Feat_296',
 'Feat_297',
 'Feat_298',
 'Feat_299',
 'Feat_300',
 'Feat_301',
 'Feat_302',
 'Feat_303',
 'Feat_304',
 'Feat_305',
 'Feat_306',
 'Feat_307',
 'Feat_308',
 'Feat_309',
 'Feat_310',
 'Feat_311',
 'Feat_312',
 'Feat_313',
 'Feat_314',
 'Feat_315',
 'Feat_316',
 'Feat_317',
 'Feat_318',
 'Feat_319',
 'Feat_320',
 'Feat_321',
 'Feat_322',
 'Feat_323',
 'Feat_324',
 'Feat_325',
 'Feat_326',
 'Feat_327',
 'Feat_328',
 'Feat_329',
 'Feat_330',
 'Feat_331',
 'Feat_332',
 'Feat_333',
 'Feat_334',
 'Feat_335',
 'Feat_336',
 'Feat_337',
 'Feat_338',
 'Feat_339',
 'Feat_340',
 'Feat_341',
 'Feat_342',
 'Feat_343',
 'Feat_344',
 'Feat_345',
 'Feat_346',
 'Feat_347',
 'Feat_348',
 'Feat_349',
 'Feat_350',
 'Feat_351',
 'Feat_352',
 'Feat_353',
 'Feat_354',
 'Feat_355',
 'Feat_356',
 'Feat_357',
 'Feat_358',
 'Feat_359',
 'Feat_360',
 'Feat_361',
 'Feat_362',
 'Feat_363',
 'Feat_364',
 'Feat_365',
 'Feat_366',
 'Feat_367',
 'Feat_368',
 'Feat_369',
 'Feat_370',
 'Feat_371',
 'Feat_372',
 'Feat_373',
 'Feat_374',
 'Feat_375',
 'Feat_376',
 'Feat_377',
 'Feat_378',
 'Feat_379',
 'Feat_380',
 'Feat_381',
 'Feat_382',
 'Feat_383',
 'Feat_384',
 'Feat_385',
 'Feat_386',
 'Feat_387',
 'Feat_388',
 'Feat_389',
 'Feat_390',
 'Feat_391',
 'Feat_392',
 'Feat_393',
 'Feat_394',
 'Feat_395',
 'Feat_396',
 'Feat_397',
 'Feat_398',
 'Feat_399',
 'Feat_400']

In [7]:
X1=df1[C]
X2=df2[C]

In [8]:
X1

,Feat_1,Feat_2,Feat_3,Feat_4,Feat_5,Feat_6,Feat_7,Feat_8,Feat_9,Feat_10,...,Feat_391,Feat_392,Feat_393,Feat_394,Feat_395,Feat_396,Feat_397,Feat_398,Feat_399,Feat_400
0,4444.0,1944.0,2164.0,2642.0,2710.0,1861.0,2468.0,3416.0,1513.0,934.0,...,4348.0,965.0,3594.0,2897.0,1707.0,385.0,1935.0,2215.0,1662.0,5653.0
1,4593.0,2115.0,2250.0,2782.0,2873.0,2011.0,2599.0,3486.0,1607.0,1054.0,...,4655.0,1273.0,3909.0,3280.0,2056.0,568.0,2135.0,2473.0,1982.0,5992.0
2,5951.0,2822.0,3526.0,3983.0,4711.0,3175.0,3580.0,4849.0,2687.0,2118.0,...,6152.0,1483.0,5334.0,4339.0,3023.0,520.0,2894.0,4260.0,2709.0,8019.0
3,12914.0,3757.0,5336.0,5229.0,8809.0,3737.0,4533.0,9285.0,4286.0,2865.0,...,13407.0,1422.0,11405.0,10797.0,6536.0,731.0,5902.0,10064.0,7908.0,17731.0
4,3969.0,1663.0,1840.0,1832.0,3375.0,1617.0,1702.0,3201.0,1416.0,1331.0,...,4957.0,29.0,3867.0,4174.0,2168.0,629.0,2104.0,3947.0,2931.0,5869.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,2643.0,-367.0,986.0,721.0,1957.0,-353.0,-322.0,1550.0,-53.0,1555.0,...,3838.0,-764.0,3002.0,3172.0,426.0,-207.0,1434.0,2262.0,1915.0,4642.0
3549,1098.0,-19.0,175.0,296.0,975.0,-36.0,-7.0,676.0,60.0,305.0,...,1424.0,-464.0,1080.0,1016.0,126.0,-293.0,384.0,911.0,728.0,1885.0
3550,2411.0,-431.0,833.0,662.0,1542.0,-397.0,-338.0,1330.0,-76.0,1462.0,...,3500.0,-685.0,2866.0,3054.0,317.0,-144.0,1325.0,2185.0,1824.0,4333.0
3551,1775.0,223.0,294.0,413.0,1429.0,271.0,307.0,991.0,120.0,589.0,...,2126.0,-434.0,1647.0,1545.0,-14.0,-455.0,543.0,1156.0,993.0,2765.0
3552,1945.0,335.0,386.0,493.0,1578.0,327.0,317.0,1146.0,136.0,534.0,...,2399.0,-540.0,1877.0,1753.0,20.0,-505.0,671.0,1477.0,1194.0,3065.0

In [9]:
X2

,Feat_1,Feat_2,Feat_3,Feat_4,Feat_5,Feat_6,Feat_7,Feat_8,Feat_9,Feat_10,...,Feat_391,Feat_392,Feat_393,Feat_394,Feat_395,Feat_396,Feat_397,Feat_398,Feat_399,Feat_400
0,3633.0,869.0,1679.0,1720.0,2908.0,1519.0,1347.0,3016.0,1477.0,2145.0,...,4274.0,-207.0,3577.0,3549.0,1631.0,1.0,1985.0,2361.0,2707.0,5470.0
1,11921.0,7506.0,6317.0,8533.0,10467.0,7454.0,8094.0,11028.0,7563.0,5708.0,...,12658.0,4364.0,11036.0,11507.0,8382.0,3012.0,6795.0,11645.0,8715.0,15698.0
2,2675.0,1056.0,1126.0,1347.0,1861.0,1098.0,1152.0,2271.0,880.0,1012.0,...,3377.0,126.0,2839.0,2572.0,1027.0,-291.0,1253.0,2372.0,1724.0,4258.0
3,8306.0,4668.0,3794.0,4960.0,7121.0,4693.0,5155.0,7262.0,4283.0,4017.0,...,8467.0,2198.0,7411.0,6932.0,4705.0,1473.0,4172.0,6581.0,4294.0,11141.0
4,8967.0,6151.0,4627.0,6536.0,7729.0,6162.0,6614.0,7994.0,6144.0,4298.0,...,9184.0,3541.0,8599.0,7807.0,5031.0,842.0,5379.0,8260.0,6138.0,12159.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,2098.0,-268.0,-145.0,-166.0,312.0,-49.0,28.0,517.0,-147.0,-155.0,...,2165.0,346.0,1731.0,1773.0,701.0,-46.0,870.0,1309.0,1209.0,2845.0
622,1698.0,-50.0,346.0,264.0,872.0,232.0,206.0,1072.0,-19.0,483.0,...,2763.0,-561.0,2118.0,2146.0,119.0,-511.0,623.0,1661.0,1139.0,3464.0
623,448.0,-52.0,36.0,64.0,30.0,-43.0,42.0,245.0,-60.0,-27.0,...,495.0,-82.0,380.0,369.0,-157.0,-95.0,86.0,151.0,123.0,514.0
624,508.0,99.0,190.0,252.0,121.0,-145.0,166.0,412.0,-27.0,96.0,...,613.0,4.0,501.0,543.0,-323.0,-51.0,183.0,394.0,247.0,695.0
625,3631.0,1109.0,1684.0,1997.0,2739.0,1470.0,1878.0,2679.0,1274.0,854.0,...,3843.0,1141.0,3328.0,2878.0,1134.0,601.0,1850.0,2582.0,2182.0,4965.0

In [10]:
df1.drop(C,inplace=True,axis=1)
df2.drop(C,inplace=True,axis=1)

In [11]:
df1.drop(["id","sequence","Length"],axis=1,inplace=True)
df2.drop(["id","sequence","Length"],axis=1,inplace=True)

In [12]:
y1=df1
y2=df2

In [13]:
col=[]
for m in y1.columns:
    col.append(m)

In [14]:
y2.columns==y1.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [15]:
models=[]
from sklearn.tree import DecisionTreeClassifier
for i in range(len(col)):
    knn=DecisionTreeClassifier()
    knn.fit(X1, y1[col[i]]) 
    # print(models.predict(X2))
    print(knn.score(X2, y2[col[i]]))
    models.append(knn)

0.8448566610455311
0.9780775716694773
0.8701517706576728
0.897133220910624
0.9426644182124789
0.9055649241146712
0.7824620573355818
0.8111298482293423
0.9679595278246206
0.6644182124789207
0.8887015177065767

In [16]:
for i in range(len(models)):
    print(models[i].score(X1, y1[col[i]]))

1.0
1.0
0.9997179921037789
1.0
1.0
1.0
0.9997179921037789

1.0
1.0
0.9997179921037789
1.0

In [17]:
for i in range(len(models)):
    print(models[i].score(X2, y2[col[i]]))

0.8448566610455311
0.9780775716694773
0.8701517706576728
0.897133220910624
0.9426644182124789
0.9055649241146712
0.7824620573355818
0.8111298482293423
0.9679595278246206
0.6644182124789207
0.8887015177065767

In [18]:
arr=y2.iloc[0,:]
arr1=[0,1,0,1,0,1,0,0,0,0,0]

In [19]:
y2[col[0]]

0      1
1      1
2      1
3      1
4      1
      ..
621    0
622    0
623    0
624    0
625    0
Name: Cellmembrane, Length: 593, dtype: int64

In [20]:
len(models[0].predict(X2))
s=0
for i in models[0].predict(X2)==y2[col[0]]:
    if i:
        s+=1
s

501

In [21]:
dd1=[]
for i in range(len(models)):
    dd1.append(models[i].predict(X1))

In [22]:
data_f1 = pd.DataFrame(dd1,index=y2.columns)

In [23]:
data_f1=data_f1.transpose()

In [24]:
y1=y1.reset_index()

In [25]:
y1.drop("index",inplace=True,axis=1)

In [26]:
y1

,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3541,0,0,0,0,0,0,0,0,0,0,1
3542,0,0,0,0,0,0,0,0,0,0,1
3543,0,0,0,0,0,0,0,0,0,0,1
3544,0,0,0,0,0,0,0,0,0,0,1
3545,0,0,0,0,0,0,0,0,0,0,1

In [27]:
sum=0
for i in range(len(y1)):
    sum+=(data_f1.iloc[i,:]==y1.iloc[i,:]).all()
sum/len(y1)

0.9994359842075579

In [28]:
dd=[]
for i in range(len(models)):
    dd.append(models[i].predict(X2))
# data_f= pd.DataFrame(dd, columns = y2.columns)

In [29]:
data_f = pd.DataFrame(dd,index=y2.columns)

In [30]:
data_f=data_f.transpose()

In [31]:
y2=y2.reset_index()

In [32]:
data_f.columns

Index(['Cellmembrane', 'Cellwall', 'Cytoplasm', 'Endoplasm', 'Extracellular',
       'Golgi Apparatus', 'Mitochondrion', 'Nucleus', 'Peroxisome', 'Plastid',
       'Vacuole'],
      dtype='object')

In [33]:
y2.drop("index",inplace=True,axis=1)

In [34]:
sum=0
for i in range(len(y2)):
    sum+=(data_f.iloc[i,:]==y2.iloc[i,:]).all()
sum/len(y2)

0.224283305227656

In [35]:
sum1=0
for i in range(len(y2)):
    c=0
    for j in range(len(y2.iloc[i])):
        if y2.iloc[i][j]==data_f.iloc[i][j]:
            c+=1
    sum1=sum1+c/len(y2.iloc[i])

sum1/len(y2)

0.8684654300168668