In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\PsePSSM_train_independent.csv")
df2=pd.read_csv(r"C:\Users\tejus\Downloads\Features\Features\Independent\PSSM\PsePSSM_test_independent.csv")

In [3]:
df1

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,...,Feat_311,Feat_312,Feat_313,Feat_314,Feat_315,Feat_316,Feat_317,Feat_318,Feat_319,Feat_320
0,Q38967,MGETAAANNHRHHHHHGHQVFDVASHDFVPPQPAFKCFDDDGRLKR...,1,0,0,0,0,0,0,0,...,19.610879,13.682008,16.585774,25.462343,16.481172,14.039749,14.412134,20.269874,19.832636,19.504184
1,Q9FF99,MDIKEDDESRVITPTELQLHDSVTARTGTLWTAVAHIITGVIGAGV...,1,0,0,0,0,0,0,0,...,20.982301,14.090708,17.535398,27.840708,18.258850,15.389381,16.022124,22.338496,20.617257,21.152655
2,Q8RXN0,MEIEASRQQTTVPVSVGGGNFPVGGLSPLSEAIWREKAPTEFVGDV...,1,0,0,0,0,0,0,0,...,17.899709,14.431686,17.149709,23.662791,16.803779,15.543605,12.486919,17.870640,20.433140,15.946221
3,Q9ZR72,MDNDGGAPPPPPTLVVEEPKKAEIRGVAFKELFRFADGLDYVLMGI...,1,0,0,0,0,0,0,0,...,20.661684,16.750590,15.370574,20.648308,12.331235,16.595594,12.383163,9.763965,13.970889,19.463415
4,Q9FJH6,MVSDASKKKAAQKKAAAAAKRGGKAAAPSKSAATSSNGVDSLSSGV...,1,0,0,0,0,0,0,0,...,20.234483,13.112069,14.498276,14.594828,10.670690,10.920690,9.562069,11.000000,12.505172,13.324138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,P09799,MVRNKSVFVVLLFSLFLSFGLLCSAKDFPGRRSEDDPQQRYEDCRK...,0,0,0,0,0,0,0,0,...,9.983051,8.318644,7.666102,15.022034,14.244068,6.218644,4.542373,15.037288,10.923729,10.150847
3549,P02855,DNAEIEKILLEEHEKETHHRRGLRDKRQQSQEKNVIVKVSKKQIEE...,0,0,0,0,0,0,0,0,...,10.903846,8.403846,8.326923,16.350000,14.326923,7.411538,4.623077,15.569231,9.803846,9.984615
3550,P09801,MVRNKSACVVLLFSLFLSFGLLCSAKDFPGRRGDDDPPKRYEDCRR...,0,0,0,0,0,0,0,0,...,9.919721,7.640489,7.568935,14.287958,13.382199,5.980803,4.691099,14.633508,10.713787,9.801047
3551,P02854,MLLAIAFLASVCVSSRSDQENPFIFKSNRFQTLYENENGHIRLLQK...,0,0,0,0,0,0,0,0,...,12.637975,8.913924,9.032911,18.108861,14.503797,6.736709,5.554430,17.493671,12.544304,12.374684
3552,P13918,MAATTMKASFPLLMLMGISFLASVCVSSRSDPQNPFIFKSNKFQTL...,0,0,0,0,0,0,0,0,...,12.439189,9.511261,8.988739,17.797297,15.761261,7.513514,5.380631,16.403153,10.903153,11.873874

In [4]:
df2

,id,sequence,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,...,Feat_311,Feat_312,Feat_313,Feat_314,Feat_315,Feat_316,Feat_317,Feat_318,Feat_319,Feat_320
0,Q9SAH3,MPSRPNPTRPKLFHNRTKTLFLILTISSSLVIFFAILYFIYHLWIS...,1,0,0,0,0,0,0,0,...,15.418021,14.883309,12.335303,15.765140,15.011817,10.791728,6.621861,21.072378,12.140325,11.636632
1,Q9ASQ6,MSIILWSFFLFFTIILSSLTNITTLASFSSLHADELNALKEIATTL...,1,0,0,0,0,0,0,0,...,29.190239,20.137450,17.276892,22.074701,20.308765,17.747012,14.791833,16.695219,17.454183,18.445219
2,Q9SIZ4,MLFKMRSFVAFVLLLSWFGSCCSLKDQAVDFLKSEDSLKKDLSSDE...,1,0,0,0,0,0,0,0,...,17.297468,13.447257,12.432489,15.293249,16.451477,12.919831,8.394515,14.888186,12.145570,12.894515
3,Q9ZQQ7,METRSKLMLLACATFSIISLVKSQNQQGFISLYCGLPSNESPYIEP...,1,0,0,0,0,0,0,0,...,21.907003,17.663605,13.500574,21.014925,21.432836,18.258324,15.725603,16.955224,20.469575,18.896670
4,C0LGK4,MVDQRRSALGFVLLLLCLVLFFDCVVVGQTQSRFSEKLILLNLRSS...,1,0,0,0,0,0,0,0,...,29.732222,18.215556,15.810000,18.834444,24.764444,20.543333,11.927778,17.784444,16.542222,18.110000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,Q9LSF6,MTSNVQLSETNSPRNQKTRPRAEKEEVDYMQRAQWLRAALLGANDG...,0,0,0,0,0,0,0,0,...,23.264706,12.117647,16.191176,15.264706,16.671569,14.024510,11.607843,17.196078,9.470588,23.745098
622,Q9FRK5,MADSQNGKSAFFFFFVSLILLFLSPSYSDVTASESDPIPYENSDAS...,0,0,0,0,0,0,0,0,...,10.722591,7.436877,6.166113,14.611296,13.028239,7.727575,5.156146,7.747508,9.956811,9.506645
623,P06673,MKMVIVLVVWLALSAASASAMQMPCPCAGLQGLYGAGAGLTTMMGA...,0,0,0,0,0,0,0,0,...,6.866667,3.454545,7.751515,6.218182,14.018182,4.327273,2.121212,9.284848,8.563636,4.127273
624,P08031,MKVLIVALALLALAASAASSTSGGCGCQTPPFHLPPPFYMPPPFYL...,0,0,0,0,0,0,0,0,...,8.732143,3.494048,7.214286,10.309524,22.166667,5.946429,3.273810,6.184524,9.386905,5.750000
625,Q8RWN2,MAEEYKEALLEKQNYHDGCPGCKVEQMKQLRRGYPYLELSFVWIIV...,0,0,0,0,0,0,0,0,...,23.513800,15.082803,18.305732,28.176221,23.881104,14.847134,12.700637,24.309979,20.133758,17.148620

In [5]:
df1.dropna(inplace=True)
df2.dropna(inplace=True)

In [6]:
C=[]
for i in range(1,321):
    C.append("Feat_"+str(i))
C

['Feat_1',
 'Feat_2',
 'Feat_3',
 'Feat_4',
 'Feat_5',
 'Feat_6',
 'Feat_7',
 'Feat_8',
 'Feat_9',
 'Feat_10',
 'Feat_11',
 'Feat_12',
 'Feat_13',
 'Feat_14',
 'Feat_15',
 'Feat_16',
 'Feat_17',
 'Feat_18',
 'Feat_19',
 'Feat_20',
 'Feat_21',
 'Feat_22',
 'Feat_23',
 'Feat_24',
 'Feat_25',
 'Feat_26',
 'Feat_27',
 'Feat_28',
 'Feat_29',
 'Feat_30',
 'Feat_31',
 'Feat_32',
 'Feat_33',
 'Feat_34',
 'Feat_35',
 'Feat_36',
 'Feat_37',
 'Feat_38',
 'Feat_39',
 'Feat_40',
 'Feat_41',
 'Feat_42',
 'Feat_43',
 'Feat_44',
 'Feat_45',
 'Feat_46',
 'Feat_47',
 'Feat_48',
 'Feat_49',
 'Feat_50',
 'Feat_51',
 'Feat_52',
 'Feat_53',
 'Feat_54',
 'Feat_55',
 'Feat_56',
 'Feat_57',
 'Feat_58',
 'Feat_59',
 'Feat_60',
 'Feat_61',
 'Feat_62',
 'Feat_63',
 'Feat_64',
 'Feat_65',
 'Feat_66',
 'Feat_67',
 'Feat_68',
 'Feat_69',
 'Feat_70',
 'Feat_71',
 'Feat_72',
 'Feat_73',
 'Feat_74',
 'Feat_75',
 'Feat_76',
 'Feat_77',
 'Feat_78',
 'Feat_79',
 'Feat_80',
 'Feat_81',
 'Feat_82',
 'Feat_83',
 'Feat_84',
 'Feat_85',
 'Feat_86',
 'Feat_87',
 'Feat_88',
 'Feat_89',
 'Feat_90',
 'Feat_91',
 'Feat_92',
 'Feat_93',
 'Feat_94',
 'Feat_95',
 'Feat_96',
 'Feat_97',
 'Feat_98',
 'Feat_99',
 'Feat_100',
 'Feat_101',
 'Feat_102',
 'Feat_103',
 'Feat_104',
 'Feat_105',
 'Feat_106',
 'Feat_107',
 'Feat_108',
 'Feat_109',
 'Feat_110',
 'Feat_111',
 'Feat_112',
 'Feat_113',
 'Feat_114',
 'Feat_115',
 'Feat_116',
 'Feat_117',
 'Feat_118',
 'Feat_119',
 'Feat_120',
 'Feat_121',
 'Feat_122',
 'Feat_123',
 'Feat_124',
 'Feat_125',
 'Feat_126',
 'Feat_127',
 'Feat_128',
 'Feat_129',
 'Feat_130',
 'Feat_131',
 'Feat_132',
 'Feat_133',
 'Feat_134',
 'Feat_135',
 'Feat_136',
 'Feat_137',
 'Feat_138',
 'Feat_139',
 'Feat_140',
 'Feat_141',
 'Feat_142',
 'Feat_143',
 'Feat_144',
 'Feat_145',
 'Feat_146',
 'Feat_147',
 'Feat_148',
 'Feat_149',
 'Feat_150',
 'Feat_151',
 'Feat_152',
 'Feat_153',
 'Feat_154',
 'Feat_155',
 'Feat_156',
 'Feat_157',
 'Feat_158',
 'Feat_159',
 'Feat_160',
 'Feat_161',
 'Feat_162',
 'Feat_163',
 'Feat_164',
 'Feat_165',
 'Feat_166',
 'Feat_167',
 'Feat_168',
 'Feat_169',
 'Feat_170',
 'Feat_171',
 'Feat_172',
 'Feat_173',
 'Feat_174',
 'Feat_175',
 'Feat_176',
 'Feat_177',
 'Feat_178',
 'Feat_179',
 'Feat_180',
 'Feat_181',
 'Feat_182',
 'Feat_183',
 'Feat_184',
 'Feat_185',
 'Feat_186',
 'Feat_187',
 'Feat_188',
 'Feat_189',
 'Feat_190',
 'Feat_191',
 'Feat_192',
 'Feat_193',
 'Feat_194',
 'Feat_195',
 'Feat_196',
 'Feat_197',
 'Feat_198',
 'Feat_199',
 'Feat_200',
 'Feat_201',
 'Feat_202',
 'Feat_203',
 'Feat_204',
 'Feat_205',
 'Feat_206',
 'Feat_207',
 'Feat_208',
 'Feat_209',
 'Feat_210',
 'Feat_211',
 'Feat_212',
 'Feat_213',
 'Feat_214',
 'Feat_215',
 'Feat_216',
 'Feat_217',
 'Feat_218',
 'Feat_219',
 'Feat_220',
 'Feat_221',
 'Feat_222',
 'Feat_223',
 'Feat_224',
 'Feat_225',
 'Feat_226',
 'Feat_227',
 'Feat_228',
 'Feat_229',
 'Feat_230',
 'Feat_231',
 'Feat_232',
 'Feat_233',
 'Feat_234',
 'Feat_235',
 'Feat_236',
 'Feat_237',
 'Feat_238',
 'Feat_239',
 'Feat_240',
 'Feat_241',
 'Feat_242',
 'Feat_243',
 'Feat_244',
 'Feat_245',
 'Feat_246',
 'Feat_247',
 'Feat_248',
 'Feat_249',
 'Feat_250',
 'Feat_251',
 'Feat_252',
 'Feat_253',
 'Feat_254',
 'Feat_255',
 'Feat_256',
 'Feat_257',
 'Feat_258',
 'Feat_259',
 'Feat_260',
 'Feat_261',
 'Feat_262',
 'Feat_263',
 'Feat_264',
 'Feat_265',
 'Feat_266',
 'Feat_267',
 'Feat_268',
 'Feat_269',
 'Feat_270',
 'Feat_271',
 'Feat_272',
 'Feat_273',
 'Feat_274',
 'Feat_275',
 'Feat_276',
 'Feat_277',
 'Feat_278',
 'Feat_279',
 'Feat_280',
 'Feat_281',
 'Feat_282',
 'Feat_283',
 'Feat_284',
 'Feat_285',
 'Feat_286',
 'Feat_287',
 'Feat_288',
 'Feat_289',
 'Feat_290',
 'Feat_291',
 'Feat_292',
 'Feat_293',
 'Feat_294',
 'Feat_295',
 'Feat_296',
 'Feat_297',
 'Feat_298',
 'Feat_299',
 'Feat_300',
 'Feat_301',
 'Feat_302',
 'Feat_303',
 'Feat_304',
 'Feat_305',
 'Feat_306',
 'Feat_307',
 'Feat_308',
 'Feat_309',
 'Feat_310',
 'Feat_311',
 'Feat_312',
 'Feat_313',
 'Feat_314',
 'Feat_315',
 'Feat_316',
 'Feat_317',
 'Feat_318',
 'Feat_319',
 'Feat_320']

In [7]:
X1=df1[C]
X2=df2[C]

In [8]:
X1

,Feat_1,Feat_2,Feat_3,Feat_4,Feat_5,Feat_6,Feat_7,Feat_8,Feat_9,Feat_10,...,Feat_311,Feat_312,Feat_313,Feat_314,Feat_315,Feat_316,Feat_317,Feat_318,Feat_319,Feat_320
0,-1.233266,-2.683570,-2.413793,-3.097363,-2.661258,-2.342799,-2.734280,-2.399594,-2.596349,-1.494929,...,19.610879,13.682008,16.585774,25.462343,16.481172,14.039749,14.412134,20.269874,19.832636,19.504184
1,-1.316916,-2.946467,-2.674518,-3.366167,-2.755889,-2.576017,-2.987152,-2.550321,-2.920771,-1.610278,...,20.982301,14.090708,17.535398,27.840708,18.258850,15.389381,16.022124,22.338496,20.617257,21.152655
2,-1.344239,-1.987198,-2.051209,-2.635846,-2.638691,-1.964438,-2.182077,-2.354196,-2.238976,-1.559033,...,17.899709,14.431686,17.149709,23.662791,16.803779,15.543605,12.486919,17.870640,20.433140,15.946221
3,-1.217729,-2.371695,-2.350700,-2.814930,-3.298600,-2.059876,-2.267496,-2.568429,-2.758942,-1.874028,...,20.661684,16.750590,15.370574,20.648308,12.331235,16.595594,12.383163,9.763965,13.970889,19.463415
4,-1.248739,-1.660504,-1.665546,-1.722689,-2.924370,-1.240336,-1.220168,-2.379832,-1.924370,-1.989916,...,20.234483,13.112069,14.498276,14.594828,10.670690,10.920690,9.562069,11.000000,12.505172,13.324138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,-1.234711,0.008264,-1.170248,-1.119008,-2.328926,0.052893,0.138843,-1.254545,-0.581818,-1.765289,...,9.983051,8.318644,7.666102,15.022034,14.244068,6.218644,4.542373,15.037288,10.923729,10.150847
3549,-0.974545,-0.338182,-0.770909,-1.112727,-2.523636,-0.210909,-0.120000,-1.320000,-0.894545,-1.392727,...,10.903846,8.403846,8.326923,16.350000,14.326923,7.411538,4.623077,15.569231,9.803846,9.984615
3550,-1.168367,0.040816,-1.113946,-1.093537,-2.108844,0.149660,0.151361,-1.215986,-0.491497,-1.765306,...,9.919721,7.640489,7.568935,14.287958,13.382199,5.980803,4.691099,14.633508,10.713787,9.801047
3551,-1.007317,-0.741463,-0.880488,-1.363415,-2.302439,-0.619512,-0.597561,-1.300000,-0.924390,-1.251220,...,12.637975,8.913924,9.032911,18.108861,14.503797,6.736709,5.554430,17.493671,12.544304,12.374684
3552,-0.956427,-0.657952,-0.949891,-1.361656,-2.324619,-0.596950,-0.514161,-1.307190,-0.875817,-1.267974,...,12.439189,9.511261,8.988739,17.797297,15.761261,7.513514,5.380631,16.403153,10.903153,11.873874

In [9]:
X2

,Feat_1,Feat_2,Feat_3,Feat_4,Feat_5,Feat_6,Feat_7,Feat_8,Feat_9,Feat_10,...,Feat_311,Feat_312,Feat_313,Feat_314,Feat_315,Feat_316,Feat_317,Feat_318,Feat_319,Feat_320
0,-1.304913,-1.005780,-1.154624,-1.319364,-2.205202,-1.335260,-0.932081,-1.452312,-1.556358,-1.731214,...,15.418021,14.883309,12.335303,15.765140,15.011817,10.791728,6.621861,21.072378,12.140325,11.636632
1,-2.240432,-2.576055,-1.901865,-2.760550,-3.688911,-2.376840,-2.461237,-2.943081,-2.873405,-2.264966,...,29.190239,20.137450,17.276892,22.074701,20.308765,17.747012,14.791833,16.695219,17.454183,18.445219
2,-1.000000,-1.582822,-1.374233,-1.867076,-2.392638,-1.406953,-1.443763,-2.036810,-1.801636,-1.447853,...,17.297468,13.447257,12.432489,15.293249,16.451477,12.919831,8.394515,14.888186,12.145570,12.894515
3,-1.830700,-2.190745,-1.506772,-2.253950,-3.395034,-1.945824,-2.106095,-2.695260,-2.355530,-1.747178,...,21.907003,17.663605,13.500574,21.014925,21.432836,18.258324,15.725603,16.955224,20.469575,18.896670
4,-1.918033,-2.220765,-1.555191,-2.481967,-3.132240,-2.042623,-2.297268,-2.434973,-2.469945,-2.015301,...,29.732222,18.215556,15.810000,18.834444,24.764444,20.543333,11.927778,17.784444,16.542222,18.110000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,0.109589,-2.634703,-2.735160,-2.954338,-3.438356,-2.378995,-2.429224,-1.744292,-2.735160,-1.931507,...,23.264706,12.117647,16.191176,15.264706,16.671569,14.024510,11.607843,17.196078,9.470588,23.745098
622,-0.285251,-0.829822,-1.081037,-1.324149,-2.265802,-0.952998,-0.909238,-1.126418,-1.228525,-1.371151,...,10.722591,7.436877,6.166113,14.611296,13.028239,7.727575,5.156146,7.747508,9.956811,9.506645
623,0.022222,-0.977778,-1.166667,-1.627778,-0.922222,0.100000,-0.816667,-1.033333,-1.044444,-0.972222,...,6.866667,3.454545,7.751515,6.218182,14.018182,4.327273,2.121212,9.284848,8.563636,4.127273
624,-0.448087,-1.114754,-1.295082,-1.841530,-1.136612,0.535519,-0.978142,-1.557377,-0.945355,-1.185792,...,8.732143,3.494048,7.214286,10.309524,22.166667,5.946429,3.273810,6.184524,9.386905,5.750000
625,-0.882716,-2.553498,-2.526749,-3.255144,-2.185185,-2.339506,-2.786008,-2.279835,-2.699588,-1.115226,...,23.513800,15.082803,18.305732,28.176221,23.881104,14.847134,12.700637,24.309979,20.133758,17.148620

In [10]:
df1.drop(C,inplace=True,axis=1)
df2.drop(C,inplace=True,axis=1)

In [11]:
df1.drop(["id","sequence","Length"],axis=1,inplace=True)
df2.drop(["id","sequence","Length"],axis=1,inplace=True)

In [12]:
y1=df1
y2=df2

In [13]:
col=[]
for m in y1.columns:
    col.append(m)

In [14]:
y2.columns==y1.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [15]:
models=[]
from sklearn.tree import DecisionTreeClassifier
for i in range(len(col)):
    knn=DecisionTreeClassifier()
    knn.fit(X1, y1[col[i]]) 
    # print(models.predict(X2))
    print(knn.score(X2, y2[col[i]]))
    models.append(knn)

0.7993254637436762
0.9898819561551433
0.8128161888701517
0.9106239460370995
0.9814502529510961
0.8920741989881956
0.8128161888701517
0.8077571669477235
0.9645868465430016
0.7133220910623946
0.8920741989881956

In [16]:
for i in range(len(models)):
    print(models[i].score(X1, y1[col[i]]))

1.0
1.0
0.9997179921037789
1.0
1.0
1.0
0.9997179921037789
1.0
1.0
0.9997179921037789
1.0

In [17]:
for i in range(len(models)):
    print(models[i].score(X2, y2[col[i]]))

0.7993254637436762
0.9898819561551433
0.8128161888701517
0.9106239460370995
0.9814502529510961
0.8920741989881956
0.8128161888701517
0.8077571669477235
0.9645868465430016
0.7133220910623946
0.8920741989881956

In [18]:
arr=y2.iloc[0,:]
arr1=[0,1,0,1,0,1,0,0,0,0,0]

In [19]:
y2[col[0]]

0      1
1      1
2      1
3      1
4      1
      ..
621    0
622    0
623    0
624    0
625    0
Name: Cellmembrane, Length: 593, dtype: int64

In [20]:
len(models[0].predict(X2))
s=0
for i in models[0].predict(X2)==y2[col[0]]:
    if i:
        s+=1
s

474

In [21]:
dd1=[]
for i in range(len(models)):
    dd1.append(models[i].predict(X1))

In [22]:
data_f1 = pd.DataFrame(dd1,index=y2.columns)

In [23]:
data_f1=data_f1.transpose()

In [24]:
y1=y1.reset_index()

In [25]:
y1.drop("index",inplace=True,axis=1)

In [26]:
y1

,Cellmembrane,Cellwall,Cytoplasm,Endoplasm,Extracellular,Golgi Apparatus,Mitochondrion,Nucleus,Peroxisome,Plastid,Vacuole
0,1,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3541,0,0,0,0,0,0,0,0,0,0,1
3542,0,0,0,0,0,0,0,0,0,0,1
3543,0,0,0,0,0,0,0,0,0,0,1
3544,0,0,0,0,0,0,0,0,0,0,1
3545,0,0,0,0,0,0,0,0,0,0,1

In [27]:
sum=0
for i in range(len(y1)):
    sum+=(data_f1.iloc[i,:]==y1.iloc[i,:]).all()
sum/len(y1)

0.9994359842075579

In [28]:
dd=[]
for i in range(len(models)):
    dd.append(models[i].predict(X2))
# data_f= pd.DataFrame(dd, columns = y2.columns)

In [29]:
data_f = pd.DataFrame(dd,index=y2.columns)

In [30]:
data_f=data_f.transpose()

In [31]:
y2=y2.reset_index()

In [32]:
data_f.columns

Index(['Cellmembrane', 'Cellwall', 'Cytoplasm', 'Endoplasm', 'Extracellular',
       'Golgi Apparatus', 'Mitochondrion', 'Nucleus', 'Peroxisome', 'Plastid',
       'Vacuole'],
      dtype='object')

In [33]:
y2.drop("index",inplace=True,axis=1)

In [34]:
sum=0
for i in range(len(y2)):
    sum+=(data_f.iloc[i,:]==y2.iloc[i,:]).all()
sum/len(y2)

0.22934232715008432

In [35]:
sum1=0
for i in range(len(y2)):
    c=0
    for j in range(len(y2.iloc[i])):
        if y2.iloc[i][j]==data_f.iloc[i][j]:
            c+=1
    sum1=sum1+c/len(y2.iloc[i])

sum1/len(y2)

0.8706116817415334